env: standard
runtime: nodejs16

instance_class: F1

automatic_scaling:
  max_instances: 1
  max_idle_instances: 1
  min_instances: 0
  min_idle_instances: 0

handlers:
  - url: /.*
    script: auto
    secure: always